version: '3'

networks:
    redisnet:

services:
    redis-master:
        container_name: master
        image: redis:5-bullseye
        volumes:
            - "./.data:/data"
        ports:
            - "6379:6379"
        networks:
            - redisnet

    redis-slave:
        container_name: slave
        image: redis:5-bullseye
        command: redis-server --slaveof redis-master 6379
        links:
          - redis-master
        volumes:
          - "./.data:/data"
        networks:
          - redisnet
 
    redis-sentinel:
        build: 
          context: ./redis-sentinel
        links:
          - redis-master
        networks:
          - redisnet

